config/routes.rb
Rails.application.routes.draw do
  resources :films
  get 'static_pages/home'
  get 'static_pages/help'

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :films
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/film_searchable.rb
# app/models/concerns/article_searcable.rb
module FilmSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    # インデックスするフィールドの一覧
    INDEX_FIELDS = %w(product_title description main_actor featured_actor).freeze

    # インデックス名
    index_name "movies_film_#{Rails.env}"

    # マッピング情報
    settings do
      mappings dynamic: 'false' do # 動的にマッピングを生成しない
        indexes :product_title, analyzer: 'kuromoji', type: 'string'
        indexes :description,   analyzer: 'kuromoji', type: 'string'
        indexes :main_actor,    analyzer: 'kuromoji', type: 'string'
        indexes :featured_actor,analyzer: 'kuromoji', type: 'string'
      end
    end

    # インデックスするデータを生成
    # @return [Hash]
    def as_indexed_json(option = {})
      self.as_json.select { |k, _| INDEX_FIELDS.include?(k) }
    end
  end

  module ClassMethods
    # indexの作成メソッド
    def create_index!
      client = __elasticsearch__.client
      client.indices.delete index: self.index_name rescue nil
      client.indices.create(index: self.index_name,
                            body: {
                              settings: self.settings.to_hash,
                              mappings: self.mappings.to_hash
                            })
    end
  end
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :films

end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :director
  belongs_to :actor
  belongs_to :genre

  include FilmSearchable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:main_actor, :featured_actor, :product_title, :description, :genre_id, :actor_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/films/_form.html.erb
<%= form_for(film) do |f| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :main_actor %>
    <%= f.text_field :main_actor %>
  </div>

  <div class="field">
    <%= f.label :featured_actor %>
    <%= f.text_field :featured_actor %>
  </div>

  <div class="field">
    <%= f.label :product_title %>
    <%= f.text_field :product_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :genre_id %>
    <%= f.number_field :genre_id %>
  </div>

  <div class="field">
    <%= f.label :actor_id %>
    <%= f.number_field :actor_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table>
  <thead>
    <tr>
      <th>Main actor</th>
      <th>Featured actor</th>
      <th>Product title</th>
      <th>Description</th>
      <th>Genre</th>
      <th>Actor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.main_actor %></td>
        <td><%= film.featured_actor %></td>
        <td><%= film.product_title %></td>
        <td><%= film.description %></td>
        <td><%= film.genre_id %></td>
        <td><%= film.actor_id %></td>
        <td><%= link_to 'Show', film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Main actor:</strong>
  <%= @film.main_actor %>
</p>

<p>
  <strong>Featured actor:</strong>
  <%= @film.featured_actor %>
</p>

<p>
  <strong>Product title:</strong>
  <%= @film.product_title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @film.description %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @film.genre_id %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @film.actor_id %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>